app/mod_auth/controllers.py
from flask import Blueprint,request,render_template,g,url_for, redirect, flash
from flask.ext.login import login_user, logout_user, current_user, login_required
from app import db, login_manager
from app.mod_auth.models import User
from .oauth import OAuthSignIn

mod_auth = Blueprint('auth', __name__, url_prefix='/auth')


@login_manager.user_loader
def load_user(userid):
    user = User.query.get(int(userid))
    if user:
        user.location = 'Odessa'
        return user


@mod_auth.route('/signout')
def signout():
    logout_user()
    g.user = None
    return redirect(url_for('index'))


@mod_auth.route('/signin', methods=['GET', 'POST'])
def signin():
    if g.user is not None and g.user.is_authenticated:
        return redirect(url_for('index'))

    return render_template('auth/login.html',
                           title='Sign In'
                           )


@mod_auth.route('/authorize/<provider>')
def oauth_authorize(provider):
    if not current_user.is_anonymous:
        return redirect(url_for('index'))
    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize()


@mod_auth.route('/callback/<provider>')
def oauth_callback(provider):
    if not current_user.is_anonymous:
        return redirect(url_for('index'))
    oauth = OAuthSignIn.get_provider(provider)
    social_id, username, email = oauth.callback()
    if social_id is None:
        flash('Authentication failed.')
        return redirect(url_for('index'))
    user = User.query.filter_by(social_id=social_id).first()
    if not user:
        username = User.make_valid_nickname(username)
        username = User.make_unique_nickname(username)
        user = User(social_id=social_id, nickname=username, email=email)
        db.session.add(user)
        db.session.commit()
    login_user(user, True)
    return redirect(url_for('index'))

app/mod_marker/controllers.py
from flask import Blueprint, request, render_template, g, jsonify, json, Response, url_for
from flask.ext.login import login_required
from app import db
import time
from app.mod_marker.models import Marker
from app.mod_marker.forms import EditMarkerForm

from datetime import datetime


mod_marker = Blueprint('marker', __name__, url_prefix='/marker')


# GET_MARKERS
@mod_marker.route('/load', methods=['GET', 'POST'])
@login_required
def load():
    respJson = json.dumps([u.as_dict for u in Marker.query.all()])
    return Response(respJson, mimetype='application/json')

##GET FORM MARKER
@mod_marker.route('/editform')
@mod_marker.route('/editform/<int:id>')
def editform(id=None):

    formReadonly = False
    if id != None:
        marker = Marker.query.filter_by(id=id).first()
        formReadonly = marker.user_id != g.user.id
        form = EditMarkerForm(obj=marker)
    else:
        form = EditMarkerForm()

    return render_template("editmarker_.html",
                             editMarkerForm=form,
                             formReadonly = formReadonly
                             )



@mod_marker.route('/delete', methods=['POST'])
def delete():
    id = int(request.form['id'])
    marker = Marker.query.filter_by(id=id).first()
    print marker.user_id
    if marker.user_id != g.user.id:
        return jsonify({'status': 'ERR'})
    db.session.delete(marker)
    db.session.commit()
    return jsonify({'status': 'OK'})

##save form to marker
def formToMarker(form):

    newMarker = Marker.query.filter_by(id=(form.id.data if form.id.data else -1)).first()
    if newMarker is None:
      newMarker = Marker()
    newMarker.latt = form.latt.data
    newMarker.long = form.long.data
    newMarker.description=form.description.data
    newMarker.water=form.water.data
    newMarker.potable=form.potable.data
    newMarker.campfire=form.campfire.data
    newMarker.shop=form.shop.data
    newMarker.maxtentcount=form.maxtentcount.data
    newMarker.owner=g.user
    return newMarker

## SAVE MARKER
@mod_marker.route('/save', methods=['POST'])
@login_required
def save():

    form = EditMarkerForm(request.form)
    print form.data

    if form.validate():
        print "VAAAAAAAAALID"
    else:
        print "NOOOOOOO________"
        print form.errors
        return jsonify({'status': 'ERR'})

    newMarker = Marker.query.filter_by(id=(form.id.data if form.id.data else -1)).first()

    if newMarker is None:
        newMarker = Marker()

    newMarker.latt = form.latt.data
    newMarker.long = form.long.data
    newMarker.description=form.description.data
    newMarker.water=form.water.data
    newMarker.potable=form.potable.data
    newMarker.campfire=form.campfire.data
    newMarker.shop=form.shop.data
    newMarker.maxtentcount=form.maxtentcount.data
    newMarker.owner=g.user

    db.session.add(newMarker)
    db.session.commit()
    print newMarker.id
    return jsonify({'status': 'OK', 'id': newMarker.id});

app/templates/base.html
<!DOCTYPE html>

<html>
  <head>
    <link href="/static/css/bootstrap.css" rel="stylesheet" media="screen">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link  href="/static/css/font-awesome.min.css" rel="stylesheet">
     <link  href="/static/css/bootstrap-social.css"rel="stylesheet">
    <link href="/static/css/main.css" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
	<script src="/static/js/moment.js"></script>
    <script src="/static/js/jquery.cookie.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/knockout/knockout-2.2.1.js"></script>
    <script src="/static/js/markerclusterer.js"></script>

    {% if request.endpoint == 'auth.signin' %}
        <link href="/static/css/login.css" rel="stylesheet">
    {%  endif %}


    {% if request.endpoint == 'index' %}

        {% include "googleMapScript.html" %}
    {%  endif %}



    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }} - Welcome</title>
    {% else %}
    <title>{{ 'Welcome to all adventurers site' }}</title>
    {% endif %}

    <header class="navbar navbar-inverse navbar-static-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="./" class="navbar-brand">A place for tent</a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">

        </li>

        <li>
          <a href="#">Profile</a>
        </li>
        <li>
          <a href="#">Contact</a>
        </li>


          {% if g.user.is_authenticated %}
          <li>
            <a href="{{  url_for("auth.signout") }}">Signout</a>
          {% endif %}
      </ul>
    </nav>
  </div>
</header>
  </head>

  <body>



	     {% block content %}{% endblock %}
	   
	 

  </body>
</html>

app/templates/editmarker.html
'<p><div class="marker-edit">'+
    '<form action="ajax-save.php" method="POST" name="SaveMarker" id="SaveMarker">'+
        '<label for="pName"><span>Place Name :</span><input type="text" name="pName" class="save-name" placeholder="Enter Title" maxlength="30" /></label><br>'+
        '<label for="pDesc"><span>Description :</span><textarea name="pDesc" class="save-desc" placeholder="Enter Address" maxlength="90"></textarea></label><br>'+
        '<label for="pType"><span>Type :</span> <select name="pType" class="save-type"><option value="restaurant">Rastaurant</option><option value="bar">Bar</option>'+
            '<option value="house">House</option></select></label>'+
        '</form>'+
    '</div></p><button name="save-marker" class="save-marker">Save Marker Details</button>'

app/templates/editmarker_.html
<span class="info-content">
    <div class="well"  style="width:300px">

        <form disabled="" id="editmarker" action="{{ url_for('marker.save') }}" method="post" name="edit">
        <div class="row">
            {{ editMarkerForm.hidden_tag() }}
            <div class="control-group{% if editMarkerForm.errors.post %} error{% endif %}">
                <label class="control-label" for="description">Place description:</label>
                 <div class="controls">
                    {{ editMarkerForm.description(readonly=formReadonly, class="save-desc", style="min-width: 100%") }}
                    {{ editMarkerForm.latt }} {{ editMarkerForm.long }} {{ editMarkerForm.id }}
                    {% for error in editMarkerForm.errors.description %}
                        <span class="help-inline">[{{error}}]</span><br>
                    {% endfor %}
                </div>
            </div>

               <div class="control-group" >
                   <div class="row">

                        <div class="controls col-xs-6">
                            {{ editMarkerForm.shop( disabled=formReadonly)  }} Shop nearby
                        </div>
                        <div class="controls col-xs-6" >
                            {{ editMarkerForm.campfire(disabled=formReadonly )  }} Campfire allowed
                        </div>
                   </div>
                </div>
                <p><div class="control-group">
                    <div class="row">
                        <div class="controls col-xs-6" >
                             {{ editMarkerForm.water(disabled=formReadonly )  }} Water
                        </div>
                        <div class="controls col-xs-6" >
                             {{ editMarkerForm.potable( disabled=formReadonly)  }} Potable water
                        </div>
                    </div>

                </div></p>
            <div class="control-group" >
                <div class="controls">
                    <label class="control-label" for="description">Max tent count: &nbsp;</label>
                        {{ editMarkerForm.maxtentcount(disabled=formReadonly) }}
                </div>
            </div>
          </div>
        </form>
    </div>
{% if not formReadonly %}
<button name="save-marker" id="saveMarker" class="save-marker">Save Marker Details</button> &nbsp;
<button name="remove-marker" id="removeMarker" class="remove-marker" title="Remove Marker">Remove Marker</button>
{% endif %}
</span>

app/templates/googleMapScript.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<script type="text/javascript"
        src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBFjVG80hTbJw4EqjmsdQ3r1W1miLIyOSg&sensor=false"></script>

<script id="entity_body" type="text/pain">{% include "editmarker_.html" %} </script>
<script type="text/javascript">

    $(document).ready(function () {
        //var mapCenter = new google.maps.LatLng(47.6145, -122.3418); //Google map Coordinates
        $.markers = [];
        //var mapCenter = new.google
        var coockieLat = $.cookie('user_lat');
        var coockieLon = $.cookie('user_lon');
        if (coockieLat && coockieLon) {
            var mapCenter = new google.maps.LatLng(coockieLat, coockieLon);
        } else {
            var mapCenter = new google.maps.LatLng(47.6145, -122.3418);
        }

        function saveLatLon(lat, lon) {

            $.cookie('user_lat', lat);
            $.cookie('user_lon', lon);

        }

        if (!navigator.geolocation) {

            // MOCK if browser doesn't support geolocation

        } else {
            navigator.geolocation.getCurrentPosition(function (position) {

                var location = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

                // Отображаем эту точку на карте
                if ((Math.abs(coockieLat - position.coords.latitude) + Math.abs(coockieLon - position.coords.longitude) ) > 0.01) {
                    map.setCenter(location);
                }
                saveLatLon(position.coords.latitude, position.coords.longitude)

            });
        }

        map_initialize(); // initialize google map
        //############### Google Map Initialize ##############
        function map_initialize() {
            var googleMapOptions =
            {
                center: mapCenter,
                zoom: 5,
                maxZoom: 18,
                minZoom: 2,
                zoomControlOptions: {
                    style: google.maps.ZoomControlStyle.SMALL
                },
                scaleControl: true,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            map = new google.maps.Map(document.getElementById("google_map"), googleMapOptions);

            //Load Markers from the JSON respond, Check (map_process.php)--!!!!!!!!!
            $.get("{{url_for('marker.load')}}", function (data) {
                $(data).each(function () {
                    var name = $(this).attr('description');
                    var form = '<button name="save-marker" class="save-marker">Save Marker Details</button> &nbsp;' +
                            '<button name="remove-marker" class="remove-marker" title="Remove Marker">Remove Marker</button>';

                    var id = $(this).attr('id');
                    var editable = $(this).attr('editable');
                    var point = new google.maps.LatLng(parseFloat($(this).attr('latt')), parseFloat($(this).attr('long')));

                    create_marker(point, name, form, id, false, false, false, "public/images/google_map_icons/pin_blue.png");
                });

                // кластеризация
                var markerCluster = new MarkerClusterer(map, $.markers);
            });


            google.maps.event.addListener(map, 'rightclick', function (event) {
                //Edit form to be displayed with new marker
                var EditForm = document.getElementById('entity_body').innerHTML;  //######EDIT FORM
                create_marker(event.latLng, 'New Marker', EditForm, 0, true, true, true, "public/images/google_map_icons/pin_green.png");
            });


        }

        //________________________________________
        // По нажатию на кнопку сохранить
        //----------------------------------------
        function onSaveClick(marker) {


            var arrForm = {};
            $.each($('#editmarker').serializeArray(), function (i, field) {
                arrForm[field.name] = field.value;
            });
            arrForm['latt'] = marker.getPosition().lat()
            arrForm['long'] = marker.getPosition().lng()
            if (false) {
                alert("Please enter Description!");
            } else {
                save_marker(marker, arrForm, ''); //call save marker function
            }
        }

        //############### Create Marker Function ##############
        function create_marker(MapPos, MapTitle, Form, id, InfoOpenDefault, DragAble, Removable, iconPath) {

            //new marker
            var marker = new google.maps.Marker({
                position: MapPos,
                map: map,
                draggable: DragAble,
                animation: google.maps.Animation.DROP,
                title: "Hello World!",
                //icon: iconPath
                id: id
            });
            $.markers.push(marker);


            var contentString = $('<div class="marker-info-win">' +
                    '<div class="marker-inner-win"><span class="info-content">' +
                    '<h2 class="marker-heading">' + MapTitle + '</h2>' +
                    Form +
                    '</span>' +

                    '</div></div>');

            var infowindow = new google.maps.InfoWindow();
            infowindow.setContent(contentString[0]);
            var removeBtn = contentString.find('button.remove-marker')[0];
            var saveBtn = contentString.find('button.save-marker')[0];

            //add click listner to remove marker button
            google.maps.event.addDomListener(removeBtn, "click", function (event) {
                remove_marker(marker);
            });

            if (typeof saveBtn !== 'undefined')
            {
                google.maps.event.addDomListener(saveBtn, "click", function (event) {
                    onSaveClick(marker)
                });
            }

            //INFO WINDOW
            google.maps.event.addListener(marker, 'click', function () {
                //alert("111");
                if (marker.id > 0) {
                    var html = $.ajax({
                        url: "{{ url_for("marker.editform") }}/" + marker.id,
                        async: false
                    }).responseText;


                    var contentString = $('<div class="marker-info-win">' +
                            '<div class="marker-inner-win"><span class="info-content">' +
                            '<h2 class="marker-heading">' + 'Edit' + '</h2>' +
                            html + ///
                            '</span>' +

                            '</div></div>');

                    infowindow.setContent(contentString[0]);
                    var markerInfo = document.getElementById("markerInfo");
                    markerInfo.innerHTML = contentString.html();
                    toggleLeftBar(markerInfo, true);
                    var saveBtn = document.getElementById("saveMarker");
                    var removeBtn = document.getElementById("removeMarker");


                    if (typeof saveBtn !== 'undefined') //continue only when save button is present
                    {
                        google.maps.event.addDomListener(saveBtn, "click", function (event) {
                            onSaveClick(marker)
                        });
                    }
                    if (typeof removeBtn !== 'undefined') //continue only when save button is present
                    {
                        google.maps.event.addDomListener(removeBtn, "click", function (event) {
                            remove_marker(marker);
                        });
                    }
                }
                //infowindow.open(map, marker); // click on marker opens info window

            });

            if (InfoOpenDefault) //whether info window should be open by default
            {

                infowindow.open(map, marker);
            }
        }

        //############### Remove Marker Function ##############
        function remove_marker(Marker) {
            /* determine whether marker is draggable
             new markers are draggable and saved markers are fixed */
            if (Marker.getDraggable()) {
                Marker.setMap(null); //just remove new marker
            }
            else {
                //Remove saved marker from DB and map using jQuery Ajax
                //var mLatLang = Marker.getPosition().toUrlValue(); //get marker position
                var myData = {del: 'true', id: Marker.id}; //post variables
                $.ajax({
                    type: "POST",
                    url: "{{ url_for("marker.delete") }}",
                    data: myData,
                    success: function (data) {
                        Marker.setMap(null);
                        //alert(data);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError); //throw any errors
                    }
                });
            }

        }

        //############### Save Marker Function ##############
        function save_marker(Marker, arrForm, replaceWin) {
            //Save new marker using jQuery Ajax
            var mLatLang = Marker.getPosition().toUrlValue(); //get marker position
            var myData = arrForm;//{form: arrForm, latlang: mLatLang }; //post variables
            //console.log(replaceWin);
            $.ajax({
                type: "POST",
                url: "{{url_for('marker.save')}}",
                data: myData,
                success: function (data) {
                    $('#id').val(data.id);

                    Marker.id = data.id;
                    //replaceWin.html(data['data1']); //replace info window with new html
                    //????????????

                    //__________
                    Marker.setDraggable(false); //set marker to fixed
                    Marker.setIcon('http://www.google.com/mapfiles/marker.png'); //replace icon
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert(thrownError); //throw any errors
                }
            });
        }

        function toggleLeftBar(sender,show) {
            var left_bar = $('#left_bar');

            if (show !== undefined) {

                    left_bar.show(400,
                            function () {
                                google.maps.event.trigger(map, "resize");
                            });
                } else {

                    left_bar[(left_bar.is(":visible") || (!show && show !== undefined)) ? "hide" : "show"](400,
                            function () {
                                google.maps.event.trigger(map, "resize");
                            });
                }
        }

        $('#splitter').click(toggleLeftBar);

    });
</script>

<style type="text/css">

</style>

app/templates/index.html
{% extends "base.html" %}
{% block content %}


    <!--<h1 class="heading">My Google Map</h1>
    <div align="center">Right Click to Drop a New Marker</div>-->


<div class="container-fluid fullsize" style="height: 95%;">

        <div id="left_bar" style="float: left; width: 300px;display: none">
            <span id="markerInfo"> !</span>

        </div>

        <div class="fullheight"  id="main_bar">

            <div class="splitter fullheight">
                <div  id="splitter"  type="button" ><</div>
            </div><div class="content">
                <div  id="google_map" ></div>
            </div>



</div>


{% endblock  %}



<!--



<div class="container-fluid fullsize">
<div class="row fullsize">
        <div class="col-lg-4 col-md-4 col-xs-4 fullheight" id="left_bar">
        </div>

        <div class="col-lg-8 col-md-8 col-xs-8 fullheight"  id="right_bar">

            <div class="splitter fullheight">
                <button  id="splitter_button"  type="button" ><</button>
            </div><div class="content">
                <div  id="google_map" ></div>
            </div>


</div>
</div>


-->

app/templates/login.html
{% extends "base.html"%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="pr-wrap">
                <div class="pass-reset">
                    <label>
                        Enter the email you signed up with</label>
                    <input type="email" placeholder="Email" />
                    <input type="submit" value="Submit" class="pass-reset-submit btn btn-success btn-sm" />
                </div>
            </div>
            <div class="wrap">
                <p class="form-title">
                    Sign In</p>

                <form class="login">
                <input type="text" placeholder="Username" disabled/>
                <input type="password" placeholder="Password" disabled />

                  <a href="{{ url_for('oauth_authorize', provider='facebook') }}" class="btn btn-block btn-social btn-lg btn-facebook">
                      <span class="fa fa-facebook"></span> Sign in with Facebook
                    </a>

                <input type="submit" value="Sign In" class="btn btn-success btn-sm disabled" />

                <div class="remember-forgot" >
                    <div class="row">
                        <div class="col-md-6">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" disabled/>
                                    Remember Me
                                </label>
                            </div>
                        </div>
                        <div class="col-md-6 forgot-pass-content hide">
                            <a href="javascription:void(0)" class="forgot-pass ">Forgot Password</a>
                        </div>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}	

app/templates/test.html
{% extends "base.html" %}
{% block content %}


    <script type="text/javascript">

     function TasksViewModel() {
        var self = this;
        self.tasks = ko.observableArray();

        self.tasks([
            {
                title: ko.observable('title #1'),
                description: ko.observable('description #1'),
                done: ko.observable(false)
            },
            {
                title: ko.observable('title #2'),
                description: ko.observable('description #2'),
                done: ko.observable(true)
            }
        ]);

        self.beginAdd = function() {
            alert("Add");
        }
        self.beginEdit = function(task) {
            alert("Edit: " + task.title());
        }
        self.remove = function(task) {
            alert("Remove: " + task.title());
        }
        self.markInProgress = function(task) {
            task.done(false);
        }
        self.markDone = function(task) {
            task.done(true);
        }
    }
    ko.applyBindings(new TasksViewModel(), $('#main')[0]);
    </script>

{% endblock %}

app/templates/Копия login.html
{% extends "base.html"%}

{% block content %}

<h1>Sign In<h1/>
<form action="" method="post" name="login">

	<p>
		Please login with your Facebook:<br>

	
        
          <p><a href="{{ url_for('oauth_authorize', provider='facebook') }}">Login with facebook</a></p>
       	
        <br>
			  
	</p>
	
	<p><input type="submit" value="Sign In"></p>
</form>
{% endblock %}	